Added meeting length pref in accounts
biit-407/biit-server pull request #114
Opened 2020-11-12 19:47 UTC by sotails

2020-11-12 19:54 UTC, stephend017 requested changes
Can you add a testcase to validate this? Also don't forget to update the wiki if you haven't already. Other than that looks good to me.

2020-11-14 19:40 UTC, sotails commented
UpdateFields is already tested with our account put test case. This is adding an additional field that can be updated.

2020-11-15 14:34 UTC, stephend017 commented
> UpdateFields is already tested with our account put test case. This is adding an additional field that can be updated.

Yes that is ccorrect, however last sprint we ran into some trouble here where some some `updateFields` were working and some weren't. Personally I dont think the extra validation and piece of mind wont hurt, however if @fatcat2 approves this as is then im fine with it.

2020-11-17 14:49 UTC, stephend017 approved these changes

2020-11-17 19:33 UTC, merged