Adding database integrations to community_handler
biit-407/biit-server pull request #20
Opened 2020-10-05 18:09 UTC by fatcat2

2020-10-05 18:11 UTC, stephend017 commented on biit_server/community_handler.py
> +    community_db.update(community_id, {"members": community["members"] + [body]})
does this make sure I can't join a community twice?

2020-10-05 18:13 UTC, stephend017 commented on tests/test_community.py
>      Tests that community post works correctly
update this docstring please

2020-10-05 18:14 UTC, stephend017 commented on tests/test_community.py
> +        assert query_data == json.loads(rv.data)
this doesn't test authentication which concerns me since only authenticated users should be able to access communities

2020-10-05 18:15 UTC, stephend017 commented on tests/test_community.py
> +
can we assert that `instance.put` is in fact called in this test

2020-10-05 18:16 UTC, stephend017 commented on tests/test_community.py
> +        instance.delete.return_value = True
can we assert that `instance.delete` is called here

2020-10-05 18:16 UTC, stephend017 commented on tests/test_community.py
> +        instance.update.return_value = True
can we assert that `instance.update` is called and with the correct parameters

2020-10-05 18:17 UTC, stephend017 commented on tests/test_community.py
> +        instance.update.return_value = True
can we assert that `instance.update` is called and with the correct parameters

2020-10-05 18:17 UTC, stephend017 requested changes
the code looks good but I would like to see the tests be improved so we can confirm that everything is implemented and working properly

2020-10-05 18:24 UTC, sotails commented on biit_server/community_handler.py
Add Auth when getting community information

2020-10-06 03:27 UTC, sotails approved these changes
Send it

2020-10-06 03:29 UTC, stephend017 approved these changes

2020-10-06 03:30 UTC, merged