Account Routing Created
biit-407/biit-server pull request #4
Opened 2020-09-17 15:47 UTC by sotails

2020-09-17 19:17 UTC, stephend017 commented on biit_server/app.py
> +                return missing_data("email", 400)
is there a way that we can make this iterate over a collection of fields, so if we need to modify or change things in the future less code is required?

2020-09-17 19:19 UTC, stephend017 requested changes
Everything looks good even the test case, just had a minor issue with the style of the request handler see comment for more info.

2020-09-17 19:47 UTC, stephend017 approved these changes

2020-09-18 18:14 UTC, fatcat2 approved these changes
lgtm

2020-09-18 20:58 UTC, merged